### ISSUE TITLE
Name correction

### ISSUE THREAD

**Issue by adonix-dev** [blogmotion/bm-bookstack-install#1]
Changer dans le read-me [FR] et [EN]:
`"En tant que root (ou via sudo) : chmod +x bm-bookstack-centos.sh && ./bm-bookstack-centos.sh"
`
En:
`"En tant que root (ou via sudo) : chmod +x bm-bookstack-centos8.sh && ./bm-bookstack-centos8.sh"`

**Comment by blogmotion** [comment]
corrigé, merci
