### ISSUE TITLE
When I use the Bookstack-install-RHEL.sh got the error regarding on the PHP version 

### ISSUE THREAD

**Issue by dennischu00** [blogmotion/bm-bookstack-install#5]
Hi Sir,

When I use this the bookstack on ALMA linux 8.9 got the following error at the last stage.

---------------------------------------------
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
Script Illuminate\Foundation\ComposerScripts::postAutoloadDump handling the post        -autoload-dump event terminated with an exception

In platform_check.php line 24:

  Composer detected issues in your platform: Your Composer dependencies requi
  re a PHP version ">= 8.0.2". You are running 7.4.33.

install [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--d        ry-run] [--download-only] [--dev] [--no-suggest] [--no-dev] [--no-autoloader] [-        -no-progress] [--no-install] [--audit] [--audit-format AUDIT-FORMAT] [-v|vv|vvv|        --verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-auto        loader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--ignore-platform-req         IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--] [<packages>...]

./bookstack-install-RHEL.sh: line 201: /var/www/BookStack/.env: Permission denie        d
Composer detected issues in your platform:

Your Composer dependencies require a PHP version ">= 8.0.2". You are running 7.4        .33.

PHP Fatal error:  Composer detected issues in your platform: Your Composer depen        dencies require a PHP version ">= 8.0.2". You are running 7.4.33. in /var/www/Bo        okStack/vendor/composer/platform_check.php on line 24
Composer detected issues in your platform:

Your Composer dependencies require a PHP version ">= 8.0.2". You are running 7.4        .33.

PHP Fatal error:  Composer detected issues in your platform: Your Composer depen        dencies require a PHP version ">= 8.0.2". You are running 7.4.33. in /var/www/Bo        okStack/vendor/composer/platform_check.php on line 24

         * 1 * PLEASE NOTE the MariaDB password root:CBoCdhOkFGsKyB
         * 2 * AND DELETE the file (or reboot) /tmp/DB_ROOT.delete
         * 3 * Logon http://localhost.localdomain or http://::1 127.0.0.1
                 -> with admin@admin.com and 'password'

         --- END OF SCRIPT (v2022.03.29) ---

**Comment by blogmotion** [comment]
Hi @dennischu00, thank you for this report.
Now fixed in [2024.02.28 version](https://github.com/blogmotion/bm-bookstack-install/blob/a6f710a4b6ba391837cdb8b0dcf03c7fd410c9cf/bookstack-install-RHEL.sh)
